@startuml

!include https://raw.githubusercontent.com/Kyrales/1C-ER-plantuml/refs/heads/extended/main.puml

title 1С Учет скидок

package УчетСкидок <<folder>> {
 
    _Справочник(Контрагенты, "Контрагенты")   
    _Справочник(КартыЛояльности, "Карты лояльности") {
        Владелец
        НомерТелефона
    }
    _Справочник(Скидки, "Скидки"){
        ТипРасчетаСкидки
        ТипСкидки
    }

     _РегистрСведений(ДействующиеСкидки, "Действующие скидки") {
        <$d> Скидка
        <$r> Действует
        СрокДействияСкидки
    }
     _РегистрСведений(ПорогиРасчетаСкидки, "Пороги расчета скидки") {
        <$d> Скидка
        <$d> ПорогПрименения
        <$r> ЗначениеСкидки
    }
    _РегистрНакопления(ОбъемЗакупокПоНакопительнойКарте, "Объем закупок по накопительной карте") {
        <$d> НакопительнаяКарта
        <$r> СуммаЗакупок    
    }    


    _Перечисление(ТипыСкидок, "Типы скидок"){
        Процент
        Сумма
    }
    _Перечисление(ТипыРасчетаСкидки, "Типы расчета скидок"){
        ФиксированныйПроцент
        ФиксированнаяСумма
        ПоКартеЛояльности
    }

    _Документ(УстановкаСкидок, "Установка скидок") {
        Скидка
        ПериодДействияНачало
        ПериодДействияКонец
        -- ПорогСкидки --
        НижняяГраницаПорога
        ЗначениеСкидки
    }
    _Документ(РасходТовара, "Расход товара") {
        Покупатель
        Склад
        Валюта
        ВидЦен
        ОбоснованиеОтгрузки
        Организация
        Скидка
        КартаЛояльности
        СуммаСкидки
        -- Товары --
        Товар
        Цена
        Количество
        Сумма
        ПроцентСкидкиРучной
        СуммаСкидкиРучной
        ПроцентСкидкиАвтоматической
        СуммаСкидкиАвтоматической
        СуммаБезСкидок       
    }
}

ТипыРасчетаСкидки --> Скидки::ТипРасчетаСкидки
ТипыСкидок --> Скидки::ТипСкидки

Контрагенты --> РасходТовара::Покупатель
Контрагенты --> КартыЛояльности::Владелец

КартыЛояльности --> РасходТовара::КартаЛояльности
КартыЛояльности --> ОбъемЗакупокПоНакопительнойКарте::НакопительнаяКарта

Скидки --> РасходТовара::Скидка
Скидки --> УстановкаСкидок::Скидка
Скидки --> ДействующиеСкидки::Скидка
Скидки --> ПорогиРасчетаСкидки::Скидка

УстановкаСкидок --> ДействующиеСкидки
УстановкаСкидок --> ПорогиРасчетаСкидки

РасходТовара --> ОбъемЗакупокПоНакопительнойКарте


@enduml